<a href="https://colab.research.google.com/github/IshaSarangi/Edureka_Notes/blob/main/Edureka_NumPy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy**

In [ ]:
import numpy as np
#creating an array
ar1 = np.array([1,2,3,4,5,6])

print(type(ar1))
print(ar1)

print(ar1.dtype)
print(ar1.shape)
print(ar1.size) #number of elements
print(ar1.ndim)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]
int64
(6,)
6
1


In [ ]:
ar2 = np.array([1,2,3,4,5,6, 'abc'])
print(type(ar2))
print(ar2) #all data converted to string

<class 'numpy.ndarray'>
['1' '2' '3' '4' '5' '6' 'abc']


In [ ]:
#arange() -> output is a numpy array while range() -> output is a list
ar3 = np.arange(1, 11)
print(ar3)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
ar = np.array([1,2,3,4,5,6])
print(ar[-1])

6


In [ ]:
#2-Dimensional array
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
print(ar.shape) #rows, columns
print(ar.ndim)
print(ar.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9


In [ ]:
print(ar[-1][-1])
print(ar[1][2])

9
6


In [ ]:
for i in np.nditer(ar): #n-dimensional iterator: allows to read data element wise
    print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
#Matrix multiplication
ar1 = np.array([[1,2,3],[4,5,6]])
ar2 = np.array([[10,11],[20,21],[30,31]])
print(ar1)
print(ar2)

[[1 2 3]
 [4 5 6]]
[[10 11]
 [20 21]
 [30 31]]


In [ ]:
ar_mul = np.dot(ar1, ar2)
print(ar_mul)

[[140 146]
 [320 335]]


In [ ]:
marks = np.array([45, 96, 85, 67, 78, 45, 90, 56, 57, 97, 90, 85, 84, 67])
print("Sum: ", marks.sum())
print("Highest Marks: ", marks.max())
print("Lowest Marks: ", marks.min())
print("Average Marks: ", marks.mean())
print("Median: ", np.median(marks))
print("Standard Deviation: ", marks.std())
print("Variance: ", marks.var())

Sum:  1042
Highest Marks:  97
Lowest Marks:  45
Average Marks:  74.42857142857143
Median:  81.0
Standard Deviation:  17.47125919787076
Variance:  305.2448979591837


In [ ]:
#Broadcasting Arthimetical Operations
lst = [10, 20, 30]
print(lst * 3)

ar = np.array([10, 20, 30])
print(ar * 3)

[10, 20, 30, 10, 20, 30, 10, 20, 30]
[30 60 90]


#**Pandas**

Reading Data

In [ ]:
#Import and Export
#Common file types: csv, excel, JSON

#Import Functions: read_csv(), read_excel(), read_json()
#Export Functions: to_csv(), to_excel(), to_json()

import pandas as pd

In [ ]:
df = pd.read_csv('/content/Social_Network_Ads.csv')
# df = pd.read_csv('/content/Social_Network_Ads.csv', index_col="User ID")
print(df)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB
None


In [ ]:
print(df.describe())

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000


In [ ]:
#setup custom index

df.set_index("User ID", inplace = True)
print(df)

          Gender  Age  EstimatedSalary  Purchased
User ID                                          
15624510    Male   19            19000          0
15810944    Male   35            20000          0
15668575  Female   26            43000          0
15603246  Female   27            57000          0
15804002    Male   19            76000          0
...          ...  ...              ...        ...
15691863  Female   46            41000          1
15706071    Male   51            23000          1
15654296  Female   50            20000          1
15755018    Male   36            33000          0
15594041  Female   49            36000          1

[400 rows x 4 columns]


Selections: Specific columns and rows

In [ ]:
print(df['EstimatedSalary'])

User ID
15624510    19000
15810944    20000
15668575    43000
15603246    57000
15804002    76000
            ...  
15691863    41000
15706071    23000
15654296    20000
15755018    33000
15594041    36000
Name: EstimatedSalary, Length: 400, dtype: int64


In [ ]:
print(df.Age)

User ID
15624510    19
15810944    35
15668575    26
15603246    27
15804002    19
            ..
15691863    46
15706071    51
15654296    50
15755018    36
15594041    49
Name: Age, Length: 400, dtype: int64


In [ ]:
#Selecting specific columns

print(df[['Age', 'EstimatedSalary']])

          Age  EstimatedSalary
User ID                       
15624510   19            19000
15810944   35            20000
15668575   26            43000
15603246   27            57000
15804002   19            76000
...       ...              ...
15691863   46            41000
15706071   51            23000
15654296   50            20000
15755018   36            33000
15594041   49            36000

[400 rows x 2 columns]


In [ ]:
#Label Based: at[], loc[]
#Condition Based: df[condition]

In [ ]:
#at[row_index, column_label] -> only one index and one label

print(df.at[15603246, 'EstimatedSalary'])

57000


In [ ]:
#Update values

df.at[15603246, 'EstimatedSalary'] = 62000 #new value
print(df)

          Gender  Age  EstimatedSalary  Purchased
User ID                                          
15624510    Male   19            19000          0
15810944    Male   35            20000          0
15668575  Female   26            43000          0
15603246  Female   27            62000          0
15804002    Male   19            76000          0
...          ...  ...              ...        ...
15691863  Female   46            41000          1
15706071    Male   51            23000          1
15654296  Female   50            20000          1
15755018    Male   36            33000          0
15594041  Female   49            36000          1

[400 rows x 4 columns]


In [ ]:
#loc[row_index_range, column_labels]

print(df.loc[15624510:15804002, ['Gender', 'Age', 'Purchased']])

          Gender  Age  Purchased
User ID                         
15624510    Male   19          0
15810944    Male   35          0
15668575  Female   26          0
15603246  Female   27          0
15804002    Male   19          0


In [ ]:
print(df.loc[15804002])

Gender              Male
Age                   19
EstimatedSalary    76000
Purchased              0
Name: 15804002, dtype: object


In [ ]:
print(df.loc[[15804002, 15603246, 15624510], ['Age', 'EstimatedSalary']])

          Age  EstimatedSalary
User ID                       
15804002   19            76000
15603246   27            62000
15624510   19            19000


In [ ]:
#Conditional Selections

print(df[(df['Age'] > 58) & (df['Gender'] == 'Female')])

          Gender  Age  EstimatedSalary  Purchased
User ID                                          
15605000  Female   59            83000          0
15707596  Female   59            42000          0
15779529  Female   60           108000          1
15688172  Female   59            76000          1
15609669  Female   59            88000          1
15807525  Female   59            29000          1
15611430  Female   60            46000          1


In [ ]:
#Random Sampling

df_new = df.sample(5)
print(df_new)

          Gender  Age  EstimatedSalary  Purchased
User ID                                          
15746203  Female   47           144000          1
15581198    Male   31            74000          0
15776348  Female   27            54000          0
15807909    Male   19            85000          0
15721007  Female   42            80000          1


In [ ]:
#Export Data DF--->File

df_new.to_excel("Selected_data.xlsx")


1. https://www.kaggle.com/learn/pandas

2. https://www.learndatasci.com/tutorials/python-pandas-tutorial-complete-introduction-for-beginners/

3. https://github.com/KeithGalli/complete-pandas-tutorial

4. https://youtu.be/UO98lJQ3QGI?list=PL-osiE80TeTvipOqomVEeZ1HRrcEvtZB_

5. https://colab.research.google.com/drive/1HYNoa8Ed0VbxPpkFF0ERNfh6wQZAQ3PJ?usp=sharing

6. https://colab.research.google.com/drive/1m2YFk1gH7w0Uqhb1mZTD5vgy42h0H9tR?usp=sharing